# Generated by Django 6.0.4 on 2026-05-27 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(blank=True, help_text='Ex: Bacharelado em Física', max_length=100, null=True)),
                ('instituto', models.CharField(blank=True, help_text='Ex: IFUSP', max_length=50, null=True)),
                ('semestre_ingresso', models.PositiveIntegerField(blank=True, help_text='Ex: 2023', null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
