# Generated by Django 6.0.4 on 2026-05-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_institucional',
            field=models.EmailField(blank=True, help_text='Ex: aluno@usp.br', max_length=255, null=True),
        ),
    ]
