# Generated by Django 6.0.4 on 2026-05-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_avaliacao_nota_didatica_avaliacao_nota_dificuldade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('sigla', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='universidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores', to='boards.universidade'),
        ),
    ]
