# Generated by Django 6.0.4 on 2026-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='visualizacoes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
