# Generated by Django 6.0.4 on 2026-06-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_professor_visualizacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=15)),
                ('universidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutos', to='boards.universidade')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='instituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores', to='boards.instituto'),
        ),
    ]
