# Generated by Django 6.0.4 on 2026-06-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_instituto_professor_instituto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
