# Generated by Django 6.0.4 on 2026-09-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_professor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='excluir_da_media',
            field=models.BooleanField(default=False),
        ),
    ]
