# Generated by Django 6.0.4 on 2026-09-23 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_avaliacoes_anonimas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('unidade', models.CharField(blank=True, max_length=150)),
                ('departamento', models.CharField(blank=True, max_length=150)),
                ('busca', models.CharField(blank=True, db_index=True, editable=False, max_length=300)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProvaAntiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{4}/[12]$', 'Use o formato 2024/1.')])),
                ('tipo', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('SUB', 'Substitutiva'), ('REC', 'Recuperação'), ('OUTRA', 'Outra')], max_length=5)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provas', to='boards.disciplina')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provas_enviadas', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to='boards.professor')),
            ],
            options={
                'verbose_name': 'prova antiga',
                'verbose_name_plural': 'provas antigas',
                'ordering': ['-semestre', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='ArquivoProva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='provas/')),
                ('miniatura', models.FileField(blank=True, upload_to='provas/miniaturas/')),
                ('tipo_conteudo', models.CharField(max_length=40)),
                ('tamanho', models.PositiveIntegerField()),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='boards.provaantiga')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
